### ISSUE TITLE
Error: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream

### ISSUE THREAD

**Issue by nicopenaloza** [deepai-org/deepai-js-client#47]
Node version: 18.13v

```js
        const deepai = require('deepai'); // OR include deepai.min.js as a script tag in your HTML
        deepai.setApiKey('MY_API_KEY');

        var result = await deepai.callStandardApi("text2img", {
            text: "I am very happy to play with the newest APIs!",
        });
```

Error output:
```
Error: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream
    at createError (C:\Users\nicop\Desktop\NameToImage\node_modules\axios\lib\core\createError.js:16:15)
    at dispatchHttpRequest (C:\Users\nicop\Desktop\NameToImage\node_modules\axios\lib\adapters\http.js:98:23)
    at new Promise (<anonymous>)
    at httpAdapter (C:\Users\nicop\Desktop\NameToImage\node_modules\axios\lib\adapters\http.js:48:10)
    at dispatchRequest (C:\Users\nicop\Desktop\NameToImage\node_modules\axios\lib\core\dispatchRequest.js:58:10)
    at Axios.request (C:\Users\nicop\Desktop\NameToImage\node_modules\axios\lib\core\Axios.js:112:15)
    at Axios.<computed> [as post] (C:\Users\nicop\Desktop\NameToImage\node_modules\axios\lib\core\Axios.js:147:17)
    at Function.wrap [as post] (C:\Users\nicop\Desktop\NameToImage\node_modules\axios\lib\helpers\bind.js:9:15)
    at DeepAI.request [as callStandardApi] (C:\Users\nicop\Desktop\NameToImage\node_modules\deepai\lib\core\DeepAI.js:100:45)
    at Object.execute (C:\Users\nicop\Desktop\NameToImage\commands\makeme.js:11:35) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'api-key': 'MY_TOKEN',
      'Content-Type': 'application/x-www-form-urlencoded',
      'client-library': 'deepai-js-client',
      'User-Agent': 'axios/0.25.0'
    },
    withCredentials: true,
    method: 'post',
    url: 'https://api.deepai.org/api/text2img',
    data: FormData { [Symbol(state)]: [Array] }
  },
  request: undefined,
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

```

**Comment by aymenitc** [comment]
The only solution right now is to downgrade node to < 18.
It is not working on 18.

**Comment by stx-chris** [comment]
Great lib, but this issue is affecting our implementation. Has a workaround been found yet? Thanks

**Comment by Awod47** [comment]
> Downgrading to v16 worked..but our stack requires v18, Any updates on this issue??

this seems to be an error with axios itself. Im working with completely different tools that also use axios and i keep getting the same thing unless I downgrade node.

**Comment by NoodleOfDeath** [comment]
This is annoying. I don't have the option to downgrade node

**Comment by ayusudi** [comment]
I need updated information about these issue

**Comment by DJStompZone** [comment]
We have made an update that we believe should address the compatibility issue with Node v18. The related changes can be found in this pull request: https://github.com/deepai-org/deepai-js-client/pull/56.

Please update to the latest version of our library and test it with Node v18. If you continue to face any problems or encounter new issues, we kindly ask that you open a new issue with the relevant details so we can assist you further.

Thank you for supporting our platform and bringing this to our attention. We value your feedback and will continue working towards ensuring a seamless experience for all our users.
